language: node_js
node_js:
- '4'
sudo: false
cache:
  directories:
  - node_modules
before_install:
- npm config set spin false
- npm install -g bower
- bower --version
- npm install phantomjs-prebuilt
- node_modules/phantomjs-prebuilt/bin/phantomjs --version
install:
- npm install
- bower install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: l6P1N5QEsIrBrSsZUWtDKYZEZJ2mSysaaSPbmYOdunPn5wtBK2EeWsTaujma/2T81Q6vu4c6RSzuQhVINdrSl8mukLs8cOkDktX7kkbcTvy4Cj0IPAZ2MMAdbEJWMS30iOuothhMBYZHaDuhHuoW8SVh6Vhc+B7m+3vId+ZBX7ryjTpf6IYJ9PWBsAo3bhvM5T10m5oa4AWCD1YnsyaOl7VzP8VDA3+MjEK1ePsJZPJ5L6gho5+Jm13ip3ZdqRzhnU0KP4T2hQtkBCDUMXpW4+Sz3lBdyhqdCBRM2F+tlYUSKCOOIuCJQJgS9TGy/yX/+8DQmD0ZCZo5TDyBGxYeVVMm1Ikkbz5oFzThCAgNYshTkZy9tCsTRs70VCUaR8WkB/UObiNoCzrVDGRQlQfxqczWEhzOxjmfdR19aaeArAOIDrpic3Us/mp2TVp7FevwcGJUBUjlmGOupkJFXlJdvfDdNgGwaEhLwbRalaTTnHYuaOjS664jLjVn/0jmpIjiJP32oAGV+B/cYp9F3gOiHByFFQsihjV6CD2pYfR3eBuPLLNEmCW0LaVCA5MOc6vukxnWsqWEc9NxDUo6zwCI5gT0fCHuvfqbbe8vJi2c7V+KzshIX7X6hujWQ4I0jugbZ/1SUxTvohDYc5ptImcPW4RLQivy+pYF848Yc/WGvXA=
  app: protected-falls-43793
  on:
    repo: koriroys/sport-frontend
